addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"   % "0.5.1")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"  % "0.15.0")
addSbtPlugin("org.scoverage"    % "sbt-scoverage" % "1.6.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"  % "2.4.2")